Vagrant.configure("2") do |config|
  config.vm.define "web" do |web| 
    web.vm.box = "generic/ubuntu2004"
    web.vm.network "private_network", ip: "100.0.0.2"
    web.vm.hostname = "master-server.com"
    web.vm.usable_port_range = 22...65535
  end
  config.vm.define "db" do |db|
    db.vm.box = "generic/ubuntu2004"
    db.vm.network "private_network", ip: "100.0.0.3"
    db.vm.hostname = "slave-server.com"
    db.vm.usable_port_range = 22...65535
end
end 
